### ISSUE TITLE
Fix tropopause height/pressure units

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [CoryMartin-NOAA/GSI-old#11]

**Comment by CoryMartin-NOAA** [comment]
@adcollard can't yet be assigned as he has not accepted the collaboration invite

**Comment by ADCollard** [comment]
Addressed in https://github.com/CoryMartin-NOAA/GSI/pull/12

**Comment by CoryMartin-NOAA** [comment]
Closed through #12
